api_login:
  path: /api/login
  controller: App\Controller\Api\AuthController::login

api_transfer:
  path: /api/transfer
  controller: App\Controller\Api\TransactionController::transfer
  methods: [POST]
